create table FLUGHAFEN (
FHC		VARCHAR(3),
LAND		VARCHAR(3),
STADT		VARCHAR(50),
NAME		VARCHAR(50),
constraint FLUGHAFEN_PS
		primary key (FHC)
);

create table FLUG (
FNR             INTEGER,
FLC		VARCHAR(2),
FLNR		INTEGER,		
VON		VARCHAR(3),
NACH		VARCHAR(3),
AB		INTEGER,
AN		INTEGER,
constraint FLUG_PS
		primary key (FNR)
)
HORIZONTAL (AB(0800,1200));


create table PASSAGIER (
PNR		INTEGER,
NAME		VARCHAR(40),
VORNAME		VARCHAR(40),		
LAND		VARCHAR(3),
constraint PASSAGIER_PS
		primary key (PNR)
)
HORIZONTAL (PNR(35,70));