create table FLUGHAFENSJ (
FHC		VARCHAR(3),
LAND		VARCHAR(3),
STADT		VARCHAR(50),
NAME		VARCHAR(50),
constraint FLUGHAFENSJ_PS
		primary key (FHC)
);

create table FLUGSJ (
FNR             INTEGER,
FLC		VARCHAR(2),
FLNR		INTEGER,		
VON		VARCHAR(3),
NACH		VARCHAR(3),
AB		INTEGER,
AN		INTEGER,
constraint FLUGSJ_PS
		primary key (FNR)
)
HORIZONTAL (AB(0800,1200));


create table PASSAGIERSJ (
PNR		INTEGER,
NAME		VARCHAR(40),
VORNAME		VARCHAR(40),		
LAND		VARCHAR(3),
constraint PASSAGIERSJ_PS
		primary key (PNR)
)
HORIZONTAL (PNR(35,70));