set echo on;

alter session set nls_language = english;
alter session set nls_date_format = 'DD-MON-YYYY';
alter session set nls_date_language = english;

--PINATUBO:
INSERT INTO TJ_PASSAGIER VALUES (1, 'Collins', 'Phil', 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (2, 'Sting', null, 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (3, 'Bush', 'Kate', 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (4, 'Jagger', 'Mick', 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (5, 'Richards', 'Keith', 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (6, 'Gabriel', 'Peter', 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (7, 'Kaas', 'Patricia', 'F  ');
INSERT INTO TJ_PASSAGIER VALUES (8, 'Lennox', 'Annie', 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (9, 'Nannini', 'Gianna', 'I  ');
INSERT INTO TJ_PASSAGIER VALUES (10, 'Meatloaf', null, 'USA');
INSERT INTO TJ_PASSAGIER VALUES (11, 'Mercury', 'Freddie', 'GB ');
INSERT INTO TJ_PASSAGIER VALUES (12, 'Niedeggen', 'Wolfgang', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (13, 'Turner', 'Tina', 'USA');

INSERT INTO TJ_PASSAGIER VALUES (14, 'John', 'Elton', null);
INSERT INTO TJ_PASSAGIER VALUES (15, 'Ramazotti', 'Eros', 'I  ');
INSERT INTO TJ_PASSAGIER VALUES (16, 'Horn', 'Guildo', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (17, 'Miosga', 'Sarah', null);
INSERT INTO TJ_PASSAGIER VALUES (18, 'Miosga', 'Pascal', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (19, 'Maiwald', 'Kai', null);
INSERT INTO TJ_PASSAGIER VALUES (20, 'Maiwald ', 'Rudi', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (21, 'Burhenne', 'Matthias', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (22, 'Militz', 'Lukas', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (23, 'Hohmeyer', 'Melanie', null);
INSERT INTO TJ_PASSAGIER VALUES (24, 'Hohmeyer', 'Holger', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (25, 'Bayer', 'Daniel', null);
INSERT INTO TJ_PASSAGIER VALUES (26, 'Bayer', 'Eberhard', 'D  ');

INSERT INTO TJ_PASSAGIER VALUES (27, 'Hennecke', 'Christian', null);
INSERT INTO TJ_PASSAGIER VALUES (28, 'Hennecke', 'Markus', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (29, 'Gueclue', 'Ilkem', null);
INSERT INTO TJ_PASSAGIER VALUES (30, 'Gueclue', 'Erdem', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (31, 'Tepel', 'Andreas', null);
INSERT INTO TJ_PASSAGIER VALUES (32, 'Tepel', 'Martin', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (35, 'Mueller', 'Tatjana', null);

INSERT INTO TJ_PASSAGIER VALUES (34, 'DELETE', 'PINATUBO', 'D ');
-- MTSHELENS:
INSERT INTO TJ_PASSAGIER VALUES (36, 'Mueller', 'Susi', null);
INSERT INTO TJ_PASSAGIER VALUES (37, 'Reinel', 'Mario', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (38, 'Reinel', 'Martin', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (39, 'Lamps', 'Bob', null);
INSERT INTO TJ_PASSAGIER VALUES (40, 'Lamps', 'Tom', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (41, 'Bostanci', 'Hueseyin', 'D  ');

INSERT INTO TJ_PASSAGIER VALUES (42, 'Bostanci', 'Sinan', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (43, 'Hahn', 'Rene', null);
INSERT INTO TJ_PASSAGIER VALUES (44, 'Hahn', 'Donald', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (45, 'Bailleu', 'Pascal', null);
INSERT INTO TJ_PASSAGIER VALUES (47, 'Hahn', 'Andre', null);
INSERT INTO TJ_PASSAGIER VALUES (48, 'Hahn', 'Thomas', null);
INSERT INTO TJ_PASSAGIER VALUES (49, 'Scholz', 'Juergen', null);
INSERT INTO TJ_PASSAGIER VALUES (50, 'Scholz', 'Gerhard', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (51, 'Harasty', 'Sascha', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (52, 'Harasty', 'Simon', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (53, 'Schmitt', 'Stefan', null);
INSERT INTO TJ_PASSAGIER VALUES (55, 'Schmitt', 'Franz', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (56, 'Mahr', 'Florian', 'D  ');

INSERT INTO TJ_PASSAGIER VALUES (57, 'Paulheim', 'Annika', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (58, 'Klomann', 'Marcel', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (59, 'Saseno', 'Widya', 'ID ');
INSERT INTO TJ_PASSAGIER VALUES (60, 'Ruppel', 'Florian', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (61, 'Knabe', 'Nico', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (62, 'Lied', 'Christian', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (63, 'Hesse', 'Sebastian', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (64, 'Meuer', 'Bjoern', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (65, 'Stock', 'Jan', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (66, 'Tobert', 'Stefan', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (67, 'Kouada', 'Hichem', 'TUN');
INSERT INTO TJ_PASSAGIER VALUES (68, 'Englert', 'Michael', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (69, 'Ksaier', 'Nejib', 'TUN');
INSERT INTO TJ_PASSAGIER VALUES (70, 'Helmke', 'Christian', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (54, 'DELETE', 'MTSHELENS', 'D ');
-- KRAKATAU
INSERT INTO TJ_PASSAGIER VALUES (71, 'Gannouni', 'Walid', 'TUN');
INSERT INTO TJ_PASSAGIER VALUES (72, 'Sanama', 'Gaspard', 'CMR');
INSERT INTO TJ_PASSAGIER VALUES (73, 'Fessi', 'Aymen', 'TUN');
INSERT INTO TJ_PASSAGIER VALUES (74, 'Pei', 'Tao', 'CHN');
INSERT INTO TJ_PASSAGIER VALUES (75, 'Dehler', 'Tatjana', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (76, 'Sprenger', 'Sebastian', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (77, 'Heinz', 'Patrik', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (78, 'Haas', 'Bastian', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (79, 'Hahn', 'Benedikt', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (80, 'Wald', 'Daniel', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (81, 'Schaefer', 'Thilo', 'D  ');
INSERT INTO TJ_PASSAGIER VALUES (82, 'Nguentcheng', 'Alexandre', 'CMR');
INSERT INTO TJ_PASSAGIER VALUES (84, 'DELETE', 'KRAKATAU', 'D ');


commit;
  