/* Generated By:JavaCC: Do not edit this line. GepardParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GepardParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int TABLE = 6;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int VARCHAR = 8;
  /** RegularExpression Id. */
  int CONSTRAINT = 9;
  /** RegularExpression Id. */
  int PRIMARYKEY = 10;
  /** RegularExpression Id. */
  int UNIQUE = 11;
  /** RegularExpression Id. */
  int HORIZONTAL = 12;
  /** RegularExpression Id. */
  int LPAREN = 13;
  /** RegularExpression Id. */
  int RPAREN = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int SYMBOL = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<CREATE>",
    "<TABLE>",
    "\"INTEGER\"",
    "\"VARCHAR\"",
    "<CONSTRAINT>",
    "<PRIMARYKEY>",
    "<UNIQUE>",
    "<HORIZONTAL>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<DIGIT>",
    "<LETTER>",
    "<SYMBOL>",
  };

}
