/* Generated By:JavaCC: Do not edit this line. GepardParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GepardParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int DROP = 6;
  /** RegularExpression Id. */
  int TABLE = 7;
  /** RegularExpression Id. */
  int INTEGER = 8;
  /** RegularExpression Id. */
  int VARCHAR = 9;
  /** RegularExpression Id. */
  int CASCADE = 10;
  /** RegularExpression Id. */
  int CONSTRAINT = 11;
  /** RegularExpression Id. */
  int CONSTRAINTS = 12;
  /** RegularExpression Id. */
  int PRIMARYKEY = 13;
  /** RegularExpression Id. */
  int UNIQUE = 14;
  /** RegularExpression Id. */
  int HORIZONTAL = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int SYMBOL = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<CREATE>",
    "<DROP>",
    "<TABLE>",
    "\"INTEGER\"",
    "\"VARCHAR\"",
    "<CASCADE>",
    "<CONSTRAINT>",
    "<CONSTRAINTS>",
    "<PRIMARYKEY>",
    "<UNIQUE>",
    "<HORIZONTAL>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<DIGIT>",
    "<LETTER>",
    "<SYMBOL>",
  };

}
